const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const html = fs.readFileSync(path.join(__dirname, '../templates/index.html'), 'utf8');
const context = {Date, state:{jotDailyActive:true, activeJotTopicId:'a', activeJotSubtopicId:'a1', jotSelectedPageIndex:0,
 jotSubtopics:[{id:'a1',topic_id:'a'},{id:'b1',topic_id:'b'}]}};
vm.createContext(context);
vm.runInContext(html.slice(html.indexOf('function nextJotReview('), html.indexOf('let jotDailySaving')), context);
const practice = context.nextJotReview(null,'practice');
assert.equal(practice.rating,'practice');
assert.equal(practice.nextReview,undefined);
const confident = context.nextJotReview(practice,'confident');
assert.equal(confident.history.length,2);
assert.equal(confident.rating,'confident');
assert.equal(context.readJotReview({dataset:{review:JSON.stringify({rating:'practice',nextReview:'2099-01-01'})}}).rating,'practice');
assert.equal(context.readJotReview({dataset:{review:'broken'}}),null);
let pages=[{chapterId:'a1',index:2,review:practice},{chapterId:'b1',index:1,review:practice},{chapterId:'b1',index:0,review:confident}];
context.jotReviewPages=()=>pages;
assert.equal(context.jotPracticeChapterIds().length,2);
context.prepareJotDailySelection();
assert.equal(context.state.jotSelectedPageIndex,2);
pages[0].review=confident;
context.prepareJotDailySelection();
assert.equal(context.state.activeJotTopicId,'b');
assert.equal(context.state.activeJotSubtopicId,'b1');
assert.equal(context.state.jotSelectedPageIndex,1);
pages[1].review=confident;
context.prepareJotDailySelection();
assert.equal(context.state.activeJotSubtopicId,'');
assert.equal(context.jotPracticeChapterIds().length,0);
assert.match(html,/if\(state.jotDailyActive&&readJotReview\(item\)\?\.rating!=="practice"\)return ""/);
assert.ok(!html.includes('scheduled for tomorrow'));
assert.ok(!html.includes('id="jotDailyPracticeNow"'));
assert.match(html,/button\.jot-rating\[aria-pressed="true"\]\{color:var\(--rating-text\)/);
console.log('Persistent ratings, legacy data, filtered selection, confident removal and selected-only colors: passed');
