const fs = require('node:fs');
const assert = require('node:assert/strict');

const page = fs.readFileSync('tools/five-minute-consultant.html', 'utf8');
const app = fs.readFileSync('app.py', 'utf8');
const home = fs.readFileSync('templates/index.html', 'utf8');

for (const match of page.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/gi)) new Function(match[1]);

assert.match(page, /FIVE-MINUTE CONSULTANT/);
assert.match(page, /Question \$\{payload\.number\} · approximately/);
assert.match(page, /\/api\/five-minute-consultant/);
assert.match(page, /Print \/ Save PDF/);
assert.match(page, /Working hypotheses/);
assert.match(page, /Evidence to collect/);
assert.match(page, /Executive slide outline/);
assert.match(page, /I’m ready — start the 5-minute timer/);
assert.match(page, /Technology opportunities/);
assert.match(page, /technologyRecommendations/);
assert.match(page, /Confirm & generate assessment/);
assert.match(page, /chat-stream/);
assert.match(page, /function renderConversation/);
assert.match(page, /more focused question/);
assert.match(page, /Frame the business problem/);
assert.match(page, /Create alternative solutions/);
assert.match(page, /Build project charter and roadmap/);
assert.match(page, /Let’s get started\. Please tell me the problem statement/);
assert.match(page, /data-understanding=\"problem\"/);
assert.match(page, /<em>1\.1<\/em>/);
assert.match(page, /<em>6\.3<\/em>/);
assert.match(page, /function beginChat/);
assert.match(page, /\.view\.interview-layout\.active\{display:grid\}/);
assert.match(page, /grid-template-columns:minmax\(520px,1fr\) clamp\(340px,27vw,430px\)/);
assert.match(page, /@media\(max-width:820px\)/);
assert.match(page, /clamp\(430px,31vw,520px\)/);
assert.match(page, /scrollbar-color:rgba\(48,221,204,\.4\)/);
assert.match(page, /\.journey-stage b\{font-size:14px/);
assert.match(page, /\.journey-stage b\{font-size:17px/);
assert.match(page, /@keyframes check-arrive/);
assert.match(page, /animation:check-arrive/);
assert.match(page, /AI DIAGNOSTIC TRACE/);
assert.match(page, /Problem identified/);
assert.match(page, /Root cause identified/);
assert.match(page, /Resolution sketched/);
assert.match(page, /Assessment unlocks when I understand the full situation/);
assert.match(page, /YOUR CONSULTING JOURNEY/);
assert.match(page, /Confirm understanding/);
assert.match(page, /Detailed assessment/);
assert.match(page, /Solution design/);
assert.match(page, /Implementation package/);
assert.match(page, /Delivery workspace/);
assert.match(page, /Project charter/);
assert.match(page, /implementationSteps/);
assert.match(page, /Select one or more options/);
assert.match(page, /function toggleSuggestion\(/);
assert.match(page, /aria-pressed="false"/);
assert.match(app, /"\/tools\/five-minute-consultant": "five-minute-consultant\.html"/);
assert.match(app, /def _five_minute_consultant\(/);
assert.match(app, /"type": "json_schema", "name": "consultant_question"/);
assert.match(app, /"type": "json_schema", "name": "five_minute_consulting_canvas"/);
assert.match(app, /Never invent or infer client-specific data/);
assert.match(app, /"technologyRecommendations"/);
assert.match(app, /"projectCharter"/);
assert.match(app, /assessment_requested/);
assert.match(app, /understandingStatement/);
assert.match(app, /rootCause/);
assert.match(app, /estimatedQuestionsRemaining/);
assert.match(app, /previousUnderstanding/);
assert.match(app, /must never regress/);
assert.match(app, /target five to seven questions/);
assert.match(app, /len\(exchanges\) >= 8/);
assert.match(app, /if len\(exchanges\) >= 8:/);
assert.match(app, /"max_output_tokens": 12000/);
assert.match(app, /timeout=180/);
assert.match(page, /Building your assessment/);
assert.match(page, /Preparing assessment, solution options and project charter/);
assert.match(app, /carry forward as an explicit open decision/);
assert.match(app, /"documented"/);
assert.match(page, /complete=new Set\(\["understood","documented"\]\)/);
assert.match(page, /previousUnderstanding:session\.understanding/);
assert.match(page, /prior\?\.status===\"understood\"\?prior:next/);
assert.match(page, /Estimated questions remaining/);
assert.match(page, /id=\"questionForecast\"/);
assert.match(app, /\"consultant\": 120/);
assert.match(app, /\"consultant-session\": 45/);
assert.match(app, /def _openai_consultant_rate_allowed/);
assert.match(app, /Every new question must explicitly build on the user's previous answers/);
assert.match(app, /tool_key == "five-minute-consultant"/);
assert.equal((home.match(/Five-Minute Consultant/g) || []).length >= 3, true);
assert.match(home, /"five-minute-consultant":"Five-Minute Consultant"/);
assert.match(home, /const pending=window\.open\("about:blank","_blank"\)/);

console.log('Five-Minute Consultant: routes, adaptive interview and structured report passed');
