const fs = require('node:fs');
const assert = require('node:assert/strict');

const html = fs.readFileSync('templates/index.html', 'utf8');
const scripts = [...html.matchAll(new RegExp('<script[^>]*>([\\s\\S]*?)</script>', 'gi'))];
scripts.forEach(match => new Function(match[1]));

assert.match(html, /id="memberWelcome"/);
assert.match(html, />Build my edge</);
assert.match(html, />Signal Radar</);
assert.match(html, /function memberNotebookProgress\(/);
assert.match(html, /function renderMemberWelcome\(/);
assert.match(html, /state\.session&&!canUseOwnerDashboard\(\)/);
assert.match(html, /await loadJotDown\(false\)/);
assert.match(html, /prefers-reduced-motion:reduce/);
assert.match(html, /\.member-progress\{display:block;position:relative;width:100%;height:6px/);
assert.match(html, /\.member-progress i\{display:block;position:absolute;inset:0 auto 0 0;max-width:100%/);
assert.match(html, /member-landing-only \.home-shell>#memberWelcome~\*/);
assert.match(html, /onclick="showMemberSignalRadar\(\)"/);
assert.match(html, /function showMemberSignalRadar\(/);
assert.match(html, /const fullHome=!state\.session\|\|canUseOwnerDashboard\(\)\|\|state\.memberHomeExpanded/);
assert.match(html, /class="member-signal-field"/);
assert.match(html, /@keyframes memberParticle/);
assert.match(html, /\.member-learning-grid\{grid-template-columns:1fr!important\}/);
assert.match(html, /\.member-welcome,\.member-welcome \*\{font-weight:400!important\}/);
assert.match(html, /grid\.innerHTML=progress\.length\?progress\.map\(/);
assert.doesNotMatch(html, /progress\.slice\(0,6\)\.map\(/);
assert.match(html, /\.member-welcome\{display:grid;grid-template-columns:minmax\(0,1\.35fr\) minmax\(320px,\.65fr\)/);
assert.match(html, /\.member-learning\{grid-column:2;grid-row:1\/3/);
assert.match(html, /\.member-learning-grid\{max-height:510px/);
assert.match(html, /src="\/assets\/member-robot-learning\.png"/);
assert.match(html, />✦ Today’s Spark</);
assert.match(html, />◷ Daily 3-Minute Challenge</);
assert.match(html, /function loadMemberDaily\(/);
assert.match(html, /function answerMemberChallenge\(/);
assert.match(html, /fetch\("\/api\/member-daily"/);
assert.match(html, />Tool Kit</);
assert.match(html, />New Learning Resources</);
assert.match(html, /id="memberRecentNotebooks"/);
assert.match(html, /function renderMemberResourceCards\(/);
assert.match(html, /\.slice\(0,4\)/);
assert.match(html, /function openMemberToolkit\(/);
assert.match(html, /function openNewLearningResources\(/);
assert.match(html, />Watch what changed in AI &amp; Tech</);
assert.match(html, /id="memberVideoModal"/);
assert.match(html, /function openMemberVideoBrief\(/);
assert.match(html, /dateRange:"24h"/);
assert.match(html, /function renderMemberVideoScene\(/);
assert.match(html, /function toggleMemberVideoVoice\(/);
assert.match(html, /#memberVideoModal\.open\{display:grid!important\}/);
assert.match(html, /fetch\("\/api\/member-video-script"/);
assert.match(html, /OpenAI is producing today’s briefing/);
assert.match(html, /AI PRODUCED/);
assert.match(html, /function memberVideoImage\(/);
assert.match(html, /class="member-video-media"/);
assert.match(html, /referrerpolicy="no-referrer"/);
assert.match(html, /@keyframes memberVideoKenBurns/);
assert.match(html, /@keyframes memberVideoLightSweep/);
assert.match(html, /id="profileFeedbackSection"/);
assert.match(html, /function submitUserFeedback\(/);
assert.match(html, /fetch\("\/api\/feedback"/);
assert.match(html, /function loadAdminFeedback\(/);
assert.match(html, /fetch\("\/api\/admin\/feedback"/);
assert.match(html, /id="notebookSavedModal"/);
assert.match(html, /function showNotebookSavedConfirmation\(/);
assert.match(html, /setLearnMode\("ask"\);await loadJotDown\(true\)/);
assert.match(html, /state\.jotWelcomePending=false;state\.jotEmptyDismissed=true;renderJotPages\(\);showNotebookSavedConfirmation/);
assert.match(html, /badge\.innerHTML=quote\?\.price!=null/);
assert.match(html, /stock-change/);
assert.match(html, /Only the administrator can delete notebooks/);
assert.match(html, /Only the administrator can delete chapters/);
assert.match(html, /jot-page-delete\[title\^="Delete notebook"\]/);
assert.match(html, /if\(!canUseOwnerDashboard\(\)\).*deleteJotTopicAdminOnly/);
assert.match(html, /id="jotExportPdfBtn"/);
assert.match(html, /function exportActiveJotNotebookPdf\(/);
for (const id of ['jotPreviewPdf','jotPreviewHtml','jotPreviewJson','jotPreviewMarkdown','jotPreviewScorm']) assert.match(html, new RegExp(`id="${id}"`));
assert.match(html, /function createJotStoredZip\(/);
assert.match(html, /imsmanifest\.xml/);
assert.match(html, /SCORM_1\.2\.zip/);
assert.match(html, /id="jotPdfPlayer"/);
assert.match(html, /function openJotPdfViewer\(/);
assert.match(html, /function closeJotPdfViewer\(/);
assert.match(html, /function bindJotAttachmentLinks\(/);
assert.match(html, /Open \$\{attachment\.name\} in PDF viewer/);
assert.match(html, /id="jotDescriptionRichMode"/);
assert.match(html, /id="jotDescriptionPlainMode"/);
assert.match(html, /function setJotDescriptionMode\(/);
assert.match(html, /jotDescriptionMode==="rich"&&html/);
assert.match(html, /sanitizeJotDescription\(clipboard\.innerHTML,false\)/);
assert.match(html, /clipboard\.content\.querySelectorAll\("img\[src\]"\)/);
assert.match(html, /Pasted explanation image/);
assert.match(html, /Some images were unavailable/);
assert.match(html, /function fetchJotPastedImageSource\(/);
assert.match(html, /fetch\("\/api\/jot-media\/import"/);
assert.match(html, /Promise\.race\(\[downloads,new Promise\(resolve=>setTimeout\(resolve,2500\)\)\]\)/);

console.log('Member welcome: personalized routes, assigned learning progress, access gating and motion fallback passed');
