const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const html=fs.readFileSync(require('node:path').join(__dirname,'../templates/index.html'),'utf8');
const source=html.slice(html.indexOf('function renderJotWorkspaceStatus(){'),html.indexOf('function hideJotLooseText('));
const nodes={};
for(const id of ['jotWorkspaceStatus','jotWorkspaceStatusTitle','jotWorkspaceStatusText','jotWorkspaceRetry','jotWorkspaceBrowse','jotWorkspaceStart'])nodes[id]={hidden:false,classList:{toggle(){}},style:{}};
const panes=Array.from({length:3},()=>({style:{}}));
nodes.jotWorkspaceStatus.parentElement={children:[nodes.jotWorkspaceStatus,...panes],setAttribute(){}};
const state={jotLoading:true,jotLoaded:false,jotTopics:[{id:'old'}],jotSubtopics:[{id:'old'}]};
let count=1;
const ctx={state,$:id=>nodes[id],jotPageCountForSubtopic:()=>count};vm.createContext(ctx);vm.runInContext(source,ctx);
ctx.renderJotWorkspaceStatus();assert.equal(nodes.jotWorkspaceStatus.hidden,false);assert.ok(panes.every(p=>p.inert&&p.style.visibility==='hidden'));
state.jotLoading=false;state.jotLoaded=true;ctx.renderJotWorkspaceStatus();assert.equal(nodes.jotWorkspaceStatus.hidden,true);assert.ok(panes.every(p=>!p.inert));
state.jotWelcomePending=true;ctx.renderJotWorkspaceStatus();assert.equal(nodes.jotWorkspaceStart.hidden,false);assert.equal(nodes.jotWorkspaceStatusTitle.textContent,'1 notebook loaded');assert.ok(panes.every(p=>p.inert));ctx.startJotWorkspaceLearning();assert.equal(nodes.jotWorkspaceStatus.hidden,true);ctx.renderJotWorkspaceStatus();assert.equal(nodes.jotWorkspaceStart.hidden,true);
state.jotTopics=[];state.jotSubtopics=[];ctx.renderJotWorkspaceStatus();assert.match(nodes.jotWorkspaceStatusText.textContent,/trainer to assign/);assert.equal(nodes.jotWorkspaceBrowse.hidden,true);
state.jotTopics=[{id:'one'}];state.jotSubtopics=[{id:'chapter'}];count=0;ctx.renderJotWorkspaceStatus();assert.match(nodes.jotWorkspaceStatusText.textContent,/do not have any pages/);assert.equal(nodes.jotWorkspaceBrowse.hidden,false);
state.jotLoadError='Network failure';ctx.renderJotWorkspaceStatus();assert.equal(nodes.jotWorkspaceRetry.hidden,false);assert.match(nodes.jotWorkspaceStatusTitle.textContent,/Unable/);
const loader=html.split(/\r?\n/).find(line=>line.startsWith('async function loadJotDown('));assert.doesNotMatch(loader,/My Notebook|jotRequest\(/);assert.match(loader,/finally\{state.jotLoading=false;renderJotWorkspaceStatus\(\)/);
console.log('Workspace loading, ready, empty, incomplete and error states passed');
