// Optional browser check: set NODE_PATH to a directory containing Playwright.
const { chromium } = require('playwright');
const path = require('path');
const fs = require('fs');
(async () => {
  const browser = await chromium.launch({headless:true, ...(process.env.MAYA_BROWSER_CHANNEL ? {channel:process.env.MAYA_BROWSER_CHANNEL} : {})});
  const page = await browser.newPage({viewport:{width:1440,height:1080}});
  const errors=[];
  page.on('pageerror', e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:8000');
  await page.getByRole('heading',{name:'Welcome to the Intelligent Experience Center.'}).waitFor();
  await page.locator('#intro-pause').click();
  if(!(await page.locator('#intro-pause').textContent()).includes('Resume'))throw Error('Intro pause control failed');
  await page.locator('#intro-pause').click();
  await page.locator('#intro-skip').click();
  await page.locator('#script-button').click();
  await page.getByRole('heading',{name:'iXHello Bot + IVR'}).waitFor();
  await page.locator('#guide-next').click();
  await page.getByRole('heading',{name:'iXHero Agent Assist'}).waitFor();
  await page.locator('#close-script').click();
  await page.locator('#reset').click();
  await page.locator('#intro-skip').click();
  await page.waitForFunction(()=>document.querySelector('#start').disabled===false);
  const output=path.resolve('data');fs.mkdirSync(output,{recursive:true});
  await page.screenshot({path:path.join(output,'maya-desktop.png'),fullPage:true});
  await page.locator('#start').click();
  await page.getByRole('heading',{name:'Calling Reseller'}).waitFor({timeout:20000});
  await page.locator('#simulate_call').click();
  await page.getByRole('heading',{name:'Calling Installation Partner'}).waitFor({timeout:10000});
  await page.locator('#simulate_call').click();
  await page.locator('.slot').first().waitFor({timeout:20000});
  await page.locator('.slot').nth(1).click();
  await page.screenshot({path:path.join(output,'maya-call.png'),fullPage:true});
  await page.locator('#complete').click();
  await page.locator('#readiness').waitFor({state:'visible'});
  await page.screenshot({path:path.join(output,'maya-ready.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:path.join(output,'maya-mobile.png'),fullPage:true});
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');
  if(errors.length)throw Error(errors.join('\n'));
  await page.locator('#reset').click();
  await page.waitForFunction(()=>document.querySelector('#start').disabled===false);
  await browser.close();
  console.log('Browser journey passed: second slot, approval, readiness, mobile width, no JavaScript errors.');
})().catch(e=>{console.error(e);process.exit(1)});
